### Introduction to Python and machine learning for economists (intermediate Python users) - FINAL EXAM

Date: 14/11/2025

**_PART 2 (10 points)_**

In [ ]:
Last name: 
First name:
Student ID:

**Data and context**

* The data are based on Giacobino, Huillery, Michel and Sage (AEJ: Applied Economics 2024). 

* This paper studies the impact of providing scholarships for secondary education to adolescent girls in Niger on the incidence of child marriage. More specifically the authors evaluate a program of the government of Niger in which girls entering middle school (approximately 13 years old) were randomly selected to receive a scholarship covering the cost of housing, food and school supplies for three years. The authors collected baseline data on all girls admitted to middle school in 2017 in 285 villages provided that they were still enrolled in school at the time of the baseline survey in December 2017. A follow-up survey was conducted in August 2020.

* You are provided with the GHMS_2024.dta database which contains data for 1,344 girls of whom 680 were randomly assigned to the scholarship (T100 = 1).
You also have access to a dictionary for all variables in the attached xlsx file (dictionary_GHMS). The treatment variable is T100 and the two key outcomes of interest are `m_gq_dropout` and `m_gq_Married`, the school enrolment status and marriage status of girls in August 2020 respectively.

* Baseline covariates are identified by the prefix ‘b_’ which is followed by ‘gq’ if the variable comes from the girls’ questionnaire (measured at the girl level) and by ‘hq’ if the variable was collected as part of the household questionnaire (information provided by an adult member of the household, generally measured at the household level).

**Assignment**

Using the GHMS_2024.dta data, you are asked to complete the tasks listed below. You will present your analysis in this Jupyter Notebook. You should comment each cell of code in your notebook to show that you understand what you are doing. You are allowed to write your comments in English or in French.

1.	Load the GHMS_2024.dta dataset in a dataframe and describe it. Hint: you will need to use the read_stata function of pandas to load the data. (/1pt)
2.  Using the sub-sample of girls assigned to the control group (C100 = 1) and the validation set approach, predict the school enrollment status of Nigerian girls approximately three years after they enter middle school (i.e: the endline enrollment status) using a **logistic** model. Use the list of baseline covariates proposed below (object `features`) as predictors. Use a seed of 3. Note: don't worry if you receive a "RuntimeWarning:" message at this stage. (/3pts)
3. Obtain the predicted values of the response variable and use them to compute the accuracy rate of your model. Compare it to the accuracy rate you would obtain if you predicted the endline enrollment status by flipping a coin. What is the percentage of improvement in accuracy that you achieve?   (/2 pts)
4. Fit a LASSO model to the same data, using the same predictors. Use 5-fold cross-validation to select the optimal lambda and a validation set to obtain the trained model. Always use a seed of 3. (/2 pts)
5. Obtain the predicted values of the response variable for the test sample of your outer split and use them to compute the accuracy rate of your LASSO model. Compare it to the accuracy rate of your logistic model. What is the percentage of improvement in accuracy that you achieve? (/1pt). Hint: To obtain the matrix of predictor values for you test sample, you can use:

`for train_idx, test_idx in outer_valid.split(X):`

    X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
    Y_train, Y_test = Y.iloc[train_idx], Y.iloc[test_idx]
 
6. Create a dataframe containing one column for the labels of predictor variables and another one with the coefficients on each predictor variable in the trained LASSO model. What is the predictor for which the coefficient has the largest absolute value? Hint : you can use DataFrame.sort_values(by = '', ascending=False) to sort your dataframe (replace DataFrame by the name of your dataframe and pass the name of the column on which you want to sort to the `by` argument). (/1pt)

Note: We would normally need to use the logistic version of LASSO given that our response variable is binary. Here, we stick to standard LASSO for simplicity.

**List of predictors to be included in your models**

features = ['b_hq_a2_wood', 'b_hq_a2_stone', 'b_hq_a2_brick', 'b_hq_a2_cement', 'b_hq_a6_Index_bw_Q2', 'b_hq_a6_Index_bw_Q3', 'b_hq_a6_Index_bw_Q4', 'b_hq_a6_Index_bw_miss', 'b_hq_d_Index_auto_cat2', 'b_hq_d_Index_auto_cat3', 'b_hq_d_Index_auto_cat4', 'b_hq_d_Index_auto_cat5', 'b_hq_d_Index_egal_cat2', 'b_hq_d_Index_egal_cat3', 'b_hq_d_Index_egal_cat4', 'b_hq_d_Index_egal_cat5', 'b_hq_e7_h', 'b_gq_age17', 'b_gq_age16', 'b_gq_age15', 'b_gq_age14', 'b_gq_age13', 'b_gq_age12', 'b_gq_age11', 'b_gq_age10', 'b_gq_c1_ever', 'b_gq_c16', 'b_gq_c26', 'b_gq_c29', 'b_gq_d42', 'b_gq_e7a_cat2m', 'b_gq_e7a_cat3m', 'b_gq_e12a_2', 'b_gq_e12a_3', 'b_gq_e12a_4', 'b_gq_e12a_5', 'b_gq_e12a_6', 'b_gq_e12a_7', 'b_gq_e12a_8', 'b_gq_g_Index_auto_cat2', 'b_gq_g_Index_auto_cat3', 'b_gq_g_Index_auto_cat4', 'b_gq_g_Index_egal_cat2', 'b_gq_g_Index_egal_cat3', 'b_gq_g_Index_egal_cat4', 'b_gq_k7_h', 'b_gq_k7_l', 'b_hh_size', 'b_hq_hh_b6', 'b_hq_hh_b9_30_35', 'b_hq_hh_b9_35_40', 'b_hq_hh_b9_40_45', 'b_hq_hh_b9_45_50', 'b_hq_hh_b9_50_55', 'b_hq_hh_b9_55_60', 'b_hq_hh_b9_60_65', 'b_hq_hh_b9_65_70', 'b_hq_hh_b9_70', 'b_hq_hh_b12a_0', 'b_hq_hh_b12a_missing', 'b_hq_hh_b10_poly', 'b_hq_hh_b10_wido', 'b_hq_hh_b17_Kanouri', 'b_hq_hh_b17_Peul', 'b_hq_hh_b17_Touareg', 'b_hq_hh_b17_Other', 'b_hq_hh_b19_1', 'b_hq_hh_b19_2', 'b_hq_hh_b19_3', 'b_hq_hh_b19_4', 'b_hq_hh_b19_5', 'b_hq_hh_b19_6', 'b_hq_hh_b18_muslim', 'b_hq_a6f_dum', 'b_hq_a6g_dum', 'b_gq_b_a_any', 'b_gq_c_40_all_16', 'b_gq_c_40_all_17', 'b_gq_c_40_all_18', 'b_gq_c_40_all_19', 'b_gq_c_40_all_20', 'b_gq_c_40_all_21', 'b_gq_c_40_all_22', 'b_gq_c_40_all_23', 'b_gq_c_40_all_24', 'b_gq_c_40_all_25', 'b_gq_c_40_all_26', 'b_gq_c_40_all_27', 'b_gq_c_40_all_28', 'b_gq_c_40_all_29', 'b_gq_c_40_all_30', 'b_gq_c_42_all', 'b_gq_d_knowledge', 'b_gq_f_control_cat2', 'b_gq_f_control_cat3', 'b_gq_f_control_cat4', 'b_gq_f_efficacite_cat2', 'b_gq_f_efficacite_cat3', 'b_gq_f_efficacite_cat4', 'b_gq_f_estime_low', 'b_gq_f_estime_ave', 'b_gq_f_estime_hig', 'b_gq_f_estime_very_hig', 'b_gq_j_sp_cat2', 'b_gq_j_sp_cat3', 'b_gq_j_sp_cat4', 'b_admin_moyenne_cat2', 'b_admin_moyenne_cat3', 'b_admin_moyenne_cat4']

In [22]:
!pip install ISLP

import pandas as pd
import numpy as np
import statsmodels.api as sm
from sklearn.model_selection import train_test_split
from sklearn.model_selection import \
     (cross_validate,
      KFold,
      ShuffleSplit)
from ISLP.models import sklearn_sm
from ISLP.models import ModelSpec as MS
import sklearn.model_selection as skm
import sklearn.linear_model as skl
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

Requirement already satisfied: ISLP in /opt/python/lib/python3.13/site-packages (0.4.0)
Requirement already satisfied: numpy>=1.7.1 in /opt/python/lib/python3.13/site-packages (from ISLP) (2.3.5)
Requirement already satisfied: scipy>=0.9 in /opt/python/lib/python3.13/site-packages (from ISLP) (1.16.3)
Requirement already satisfied: pandas>=0.20 in /opt/python/lib/python3.13/site-packages (from ISLP) (2.3.3)
Requirement already satisfied: lxml in /opt/python/lib/python3.13/site-packages (from ISLP) (6.0.2)
Requirement already satisfied: scikit-learn>=1.2 in /opt/python/lib/python3.13/site-packages (from ISLP) (1.7.2)
Requirement already satisfied: joblib in /opt/python/lib/python3.13/site-packages (from ISLP) (1.5.2)
Requirement already satisfied: statsmodels>=0.13 in /opt/python/lib/python3.13/site-packages (from ISLP) (0.14.5)
Requirement already satisfied: lifelines in /opt/python/lib/python3.13/site-packages (from ISLP) (0.30.0)
Requirement already satisfied: pygam in /opt/python/lib/python3.13/site-packages (from ISLP) (0.11.0)
Requirement already satisfied: torch in /opt/python/lib/python3.13/site-packages (from ISLP) (2.9.1)
Requirement already satisfied: pytorch-lightning in /opt/python/lib/python3.13/site-packages (from ISLP) (2.6.0)
Requirement already satisfied: torchmetrics in /opt/python/lib/python3.13/site-packages (from ISLP) (1.8.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/python/lib/python3.13/site-packages (from pandas>=0.20->ISLP) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/python/lib/python3.13/site-packages (from pandas>=0.20->ISLP) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/python/lib/python3.13/site-packages (from pandas>=0.20->ISLP) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/python/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=0.20->ISLP) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/python/lib/python3.13/site-packages (from scikit-learn>=1.2->ISLP) (3.6.0)
Requirement already satisfied: patsy>=0.5.6 in /opt/python/lib/python3.13/site-packages (from statsmodels>=0.13->ISLP) (1.0.2)
Requirement already satisfied: packaging>=21.3 in /opt/python/lib/python3.13/site-packages (from statsmodels>=0.13->ISLP) (25.0)
Requirement already satisfied: matplotlib>=3.0 in /opt/python/lib/python3.13/site-packages (from lifelines->ISLP) (3.10.7)
Requirement already satisfied: autograd>=1.5 in /opt/python/lib/python3.13/site-packages (from lifelines->ISLP) (1.8.0)
Requirement already satisfied: autograd-gamma>=0.3 in /opt/python/lib/python3.13/site-packages (from lifelines->ISLP) (0.5.0)
Requirement already satisfied: formulaic>=0.2.2 in /opt/python/lib/python3.13/site-packages (from lifelines->ISLP) (1.2.1)
Requirement already satisfied: interface-meta>=1.2.0 in /opt/python/lib/python3.13/site-packages (from formulaic>=0.2.2->lifelines->ISLP) (1.3.0)
Requirement already satisfied: narwhals>=1.17 in /opt/python/lib/python3.13/site-packages (from formulaic>=0.2.2->lifelines->ISLP) (2.12.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /opt/python/lib/python3.13/site-packages (from formulaic>=0.2.2->lifelines->ISLP) (4.15.0)
Requirement already satisfied: wrapt>=1.17.0rc1 in /opt/python/lib/python3.13/site-packages (from formulaic>=0.2.2->lifelines->ISLP) (1.17.3)
Requirement already satisfied: contourpy>=1.0.1 in /opt/python/lib/python3.13/site-packages (from matplotlib>=3.0->lifelines->ISLP) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/python/lib/python3.13/site-packages (from matplotlib>=3.0->lifelines->ISLP) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/python/lib/python3.13/site-packages (from matplotlib>=3.0->lifelines->ISLP) (4.61.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/python/lib/python3.13/site-packages (from matplotlib>=3.0->lifelines->ISLP) (1.4.9)
Requirement already satisfied: pillow>=8 in /opt/python/lib/python3.13/site-packages (from matplotlib>=3.0->lifelines->ISLP) (12.0.0)
Requirement already satisfied: pyparsing>=3 in /opt/python/lib/python3.13/site-packages (from matplotlib>=3.0->lifelines->ISLP) (3.2.5)
Requirement already satisfied: progressbar2<5,>=4.2.0 in /opt/python/lib/python3.13/site-packages (from pygam->ISLP) (4.5.0)
Requirement already satisfied: python-utils>=3.8.1 in /opt/python/lib/python3.13/site-packages (from progressbar2<5,>=4.2.0->pygam->ISLP) (3.9.1)
Requirement already satisfied: tqdm>=4.57.0 in /opt/python/lib/python3.13/site-packages (from pytorch-lightning->ISLP) (4.67.1)
Requirement already satisfied: PyYAML>5.4 in /opt/python/lib/python3.13/site-packages (from pytorch-lightning->ISLP) (6.0.3)
Requirement already satisfied: fsspec>=2022.5.0 in /opt/python/lib/python3.13/site-packages (from fsspec[http]>=2022.5.0->pytorch-lightning->ISLP) (2025.10.0)
Requirement already satisfied: lightning-utilities>=0.10.0 in /opt/python/lib/python3.13/site-packages (from pytorch-lightning->ISLP) (0.15.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /opt/python/lib/python3.13/site-packages (from fsspec[http]>=2022.5.0->pytorch-lightning->ISLP) (3.13.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /opt/python/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning->ISLP) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /opt/python/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning->ISLP) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /opt/python/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning->ISLP) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/python/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning->ISLP) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/python/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning->ISLP) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /opt/python/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning->ISLP) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /opt/python/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning->ISLP) (1.22.0)
Requirement already satisfied: idna>=2.0 in /opt/python/lib/python3.13/site-packages (from yarl<2.0,>=1.17.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning->ISLP) (3.11)
Requirement already satisfied: setuptools in /opt/python/lib/python3.13/site-packages (from lightning-utilities>=0.10.0->pytorch-lightning->ISLP) (80.9.0)
Requirement already satisfied: filelock in /opt/python/lib/python3.13/site-packages (from torch->ISLP) (3.20.0)
Requirement already satisfied: sympy>=1.13.3 in /opt/python/lib/python3.13/site-packages (from torch->ISLP) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /opt/python/lib/python3.13/site-packages (from torch->ISLP) (3.6)
Requirement already satisfied: jinja2 in /opt/python/lib/python3.13/site-packages (from torch->ISLP) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /opt/python/lib/python3.13/site-packages (from torch->ISLP) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /opt/python/lib/python3.13/site-packages (from torch->ISLP) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /opt/python/lib/python3.13/site-packages (from torch->ISLP) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /opt/python/lib/python3.13/site-packages (from torch->ISLP) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /opt/python/lib/python3.13/site-packages (from torch->ISLP) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /opt/python/lib/python3.13/site-packages (from torch->ISLP) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /opt/python/lib/python3.13/site-packages (from torch->ISLP) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /opt/python/lib/python3.13/site-packages (from torch->ISLP) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /opt/python/lib/python3.13/site-packages (from torch->ISLP) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /opt/python/lib/python3.13/site-packages (from torch->ISLP) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /opt/python/lib/python3.13/site-packages (from torch->ISLP) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /opt/python/lib/python3.13/site-packages (from torch->ISLP) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /opt/python/lib/python3.13/site-packages (from torch->ISLP) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /opt/python/lib/python3.13/site-packages (from torch->ISLP) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /opt/python/lib/python3.13/site-packages (from torch->ISLP) (1.13.1.3)
Requirement already satisfied: triton==3.5.1 in /opt/python/lib/python3.13/site-packages (from torch->ISLP) (3.5.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /opt/python/lib/python3.13/site-packages (from sympy>=1.13.3->torch->ISLP) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/python/lib/python3.13/site-packages (from jinja2->torch->ISLP) (3.0.3)

**1. Load the GHMS_2024.dta dataset in a dataframe and describe it. Hint: you will need to use the read_stata function of pandas to load the data.**

In [2]:
ghms = pd.read_stata('GHMS_2024.dta')
ghms.describe()

,hh_id,sample,clus,T100,C100,m_gq_dropout,m_gq_Married,b_hq_a2_wood,b_hq_a2_stone,b_hq_a2_brick,...,b_gq_f_estime_ave,b_gq_f_estime_hig,b_gq_f_estime_very_hig,b_gq_j_sp_cat1,b_gq_j_sp_cat2,b_gq_j_sp_cat3,b_gq_j_sp_cat4,b_admin_moyenne_cat2,b_admin_moyenne_cat3,b_admin_moyenne_cat4
count,1344.000000,1344.0,1344.000000,1344.000000,1344.000000,1344.000000,1344.000000,1344.000000,1344.000000,1344.00000,...,1344.000000,1344.000000,1344.000000,1344.000000,1344.000000,1344.000000,1344.000000,1344.000000,1344.000000,1344.000000
mean,2186.673363,1.0,144.235119,0.505952,0.494048,0.297619,0.107887,0.123512,0.273065,0.05878,...,0.316964,0.234375,0.002232,0.158482,0.409970,0.272321,0.159226,0.272321,0.200149,0.122024
std,685.601257,0.0,84.506538,0.500151,0.500151,0.457381,0.310353,0.329146,0.445700,0.23530,...,0.465467,0.423765,0.047210,0.365328,0.492011,0.445320,0.366023,0.445320,0.400260,0.327435
min,1001.000000,1.0,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1597.750000,1.0,66.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2162.500000,1.0,146.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2814.250000,1.0,215.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.00000,...,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000
max,3366.000000,1.0,284.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

**2. Using the sub-sample of girls assigned to the control group (C100 = 1) and the validation set approach, predict the school enrollment status of Nigerian girls approximately three years after they enter middle school (endline enrollment status) using a logit model. Use all available baseline covariates as predictors. Use a seed of 3. Hint: you will need to drop a few variables which do not make sense as predictors from the list of predictors (such as the unique IDs of individuals and households, you can also drop the strata).**

In [28]:
features = ['b_hq_a2_wood', 'b_hq_a2_stone', 'b_hq_a2_brick', 'b_hq_a2_cement', 'b_hq_a6_Index_bw_Q2', 'b_hq_a6_Index_bw_Q3', 'b_hq_a6_Index_bw_Q4', 'b_hq_a6_Index_bw_miss', 'b_hq_d_Index_auto_cat2', 'b_hq_d_Index_auto_cat3', 'b_hq_d_Index_auto_cat4', 'b_hq_d_Index_auto_cat5', 'b_hq_d_Index_egal_cat2', 'b_hq_d_Index_egal_cat3', 'b_hq_d_Index_egal_cat4', 'b_hq_d_Index_egal_cat5', 'b_hq_e7_h', 'b_gq_age17', 'b_gq_age16', 'b_gq_age15', 'b_gq_age14', 'b_gq_age13', 'b_gq_age12', 'b_gq_age11', 'b_gq_age10', 'b_gq_c1_ever', 'b_gq_c16', 'b_gq_c26', 'b_gq_c29', 'b_gq_d42', 'b_gq_e7a_cat2m', 'b_gq_e7a_cat3m', 'b_gq_e12a_2', 'b_gq_e12a_3', 'b_gq_e12a_4', 'b_gq_e12a_5', 'b_gq_e12a_6', 'b_gq_e12a_7', 'b_gq_e12a_8', 'b_gq_g_Index_auto_cat2', 'b_gq_g_Index_auto_cat3', 'b_gq_g_Index_auto_cat4', 'b_gq_g_Index_egal_cat2', 'b_gq_g_Index_egal_cat3', 'b_gq_g_Index_egal_cat4', 'b_gq_k7_h', 'b_gq_k7_l', 'b_hh_size', 'b_hq_hh_b6', 'b_hq_hh_b9_30_35', 'b_hq_hh_b9_35_40', 'b_hq_hh_b9_40_45', 'b_hq_hh_b9_45_50', 'b_hq_hh_b9_50_55', 'b_hq_hh_b9_55_60', 'b_hq_hh_b9_60_65', 'b_hq_hh_b9_65_70', 'b_hq_hh_b9_70', 'b_hq_hh_b12a_0', 'b_hq_hh_b12a_missing', 'b_hq_hh_b10_poly', 'b_hq_hh_b10_wido', 'b_hq_hh_b17_Kanouri', 'b_hq_hh_b17_Peul', 'b_hq_hh_b17_Touareg', 'b_hq_hh_b17_Other', 'b_hq_hh_b19_1', 'b_hq_hh_b19_2', 'b_hq_hh_b19_3', 'b_hq_hh_b19_4', 'b_hq_hh_b19_5', 'b_hq_hh_b19_6', 'b_hq_hh_b18_muslim', 'b_hq_a6f_dum', 'b_hq_a6g_dum', 'b_gq_b_a_any', 'b_gq_c_40_all_16', 'b_gq_c_40_all_17', 'b_gq_c_40_all_18', 'b_gq_c_40_all_19', 'b_gq_c_40_all_20', 'b_gq_c_40_all_21', 'b_gq_c_40_all_22', 'b_gq_c_40_all_23', 'b_gq_c_40_all_24', 'b_gq_c_40_all_25', 'b_gq_c_40_all_26', 'b_gq_c_40_all_27', 'b_gq_c_40_all_28', 'b_gq_c_40_all_29', 'b_gq_c_40_all_30', 'b_gq_c_42_all', 'b_gq_d_knowledge', 'b_gq_f_control_cat2', 'b_gq_f_control_cat3', 'b_gq_f_control_cat4', 'b_gq_f_efficacite_cat2', 'b_gq_f_efficacite_cat3', 'b_gq_f_efficacite_cat4', 'b_gq_f_estime_low', 'b_gq_f_estime_ave', 'b_gq_f_estime_hig', 'b_gq_f_estime_very_hig', 'b_gq_j_sp_cat2', 'b_gq_j_sp_cat3', 'b_gq_j_sp_cat4', 'b_admin_moyenne_cat2', 'b_admin_moyenne_cat3', 'b_admin_moyenne_cat4']

In [29]:
#Filter dataframe and select relevant columns
filt = ghms['C100'] == 1
df = ghms.loc[filt, :]

In [30]:
#Create response vector Y and matrix of predictors X

df_train, df_test = train_test_split(df,
                                         test_size=0.25,
                                         random_state=3)

Y_train, Y_test = df_train['m_gq_dropout'], df_test['m_gq_dropout']


X_train, X_test = df_train[features], df_test[features]

In [36]:
#Standardize and add constants to X matrices
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_train_std = sm.add_constant(X_train_scaled) 
X_test_std = np.hstack([np.ones((X_test_scaled.shape[0], 1)), X_test_scaled]) 

#Fit logistic model on training data
glm = sm.GLM(Y_train,
             X_train_std,
             family=sm.families.Binomial())
results_logit = glm.fit()
results_logit.summary()

/opt/python/lib/python3.13/site-packages/statsmodels/genmod/families/links.py:198: RuntimeWarning: overflow encountered in exp
  t = np.exp(-z)
/opt/python/lib/python3.13/site-packages/statsmodels/genmod/families/family.py:1056: RuntimeWarning: divide by zero encountered in log
  special.gammaln(n - y + 1) + y * np.log(mu / (1 - mu + 1e-20)) +
/opt/python/lib/python3.13/site-packages/statsmodels/genmod/families/family.py:1056: RuntimeWarning: invalid value encountered in multiply
  special.gammaln(n - y + 1) + y * np.log(mu / (1 - mu + 1e-20)) +

<class 'statsmodels.iolib.summary.Summary'>
"""
                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:           m_gq_dropout   No. Observations:                  498
Model:                            GLM   Df Residuals:                      395
Model Family:                Binomial   Df Model:                          102
Link Function:                  Logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                    nan
Date:                Mon, 01 Dec 2025   Deviance:                       14644.
Time:                        13:59:03   Pearson chi2:                 7.16e+17
No. Iterations:                    56   Pseudo R-squ. (CS):                nan
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const      -4.008e+14   3.01e+06  -1.33e+08      0.000   -4.01e+14   -4.01e+14
x1         -1.439e+14   3.59e+06  -4.01e+07      0.000   -1.44e+14   -1.44e+14
x2         -1.947e+14   3.61e+06  -5.39e+07      0.000   -1.95e+14   -1.95e+14
x3         -2.086e+14   3.58e+06  -5.83e+07      0.000   -2.09e+14   -2.09e+14
x4         -2.404e+14   3.52e+06  -6.83e+07      0.000    -2.4e+14    -2.4e+14
x5          2.048e+14   4.09e+06   5.01e+07      0.000    2.05e+14    2.05e+14
x6         -6.051e+13   4.34e+06  -1.39e+07      0.000   -6.05e+13   -6.05e+13
x7          6.557e+13   4.61e+06   1.42e+07      0.000    6.56e+13    6.56e+13
x8             0.8984   5.55e-08   1.62e+07      0.000       0.898       0.898
x9         -8.893e+13   1.39e+07  -6.39e+06      0.000   -8.89e+13   -8.89e+13
x10        -3.169e+13   1.87e+07  -1.69e+06      0.000   -3.17e+13   -3.17e+13
x11        -4.733e+13   1.73e+07  -2.73e+06      0.000   -4.73e+13   -4.73e+13
x12           -0.7298   3.84e-08   -1.9e+07      0.000      -0.730      -0.730
x13         1.797e+14   3.79e+06   4.74e+07      0.000     1.8e+14     1.8e+14
x14         1.783e+13   3.66e+06   4.86e+06      0.000    1.78e+13    1.78e+13
x15         1.258e+14   3.46e+06   3.64e+07      0.000    1.26e+14    1.26e+14
x16           -0.0444   3.77e-08  -1.18e+06      0.000      -0.044      -0.044
x17         3.745e+13   3.46e+06   1.08e+07      0.000    3.74e+13    3.74e+13
x18         2.972e+14   5.37e+06   5.53e+07      0.000    2.97e+14    2.97e+14
x19        -2.806e+13    8.4e+06  -3.34e+06      0.000   -2.81e+13   -2.81e+13
x20        -9.247e+13   1.14e+07  -8.08e+06      0.000   -9.25e+13   -9.25e+13
x21        -1.796e+14   1.91e+07  -9.42e+06      0.000    -1.8e+14    -1.8e+14
x22        -6.104e+13   2.09e+07  -2.93e+06      0.000    -6.1e+13    -6.1e+13
x23         5.834e+13   1.74e+07   3.35e+06      0.000    5.83e+13    5.83e+13
x24        -2.319e+14   8.47e+06  -2.74e+07      0.000   -2.32e+14   -2.32e+14
x25        -6.195e+14   3.86e+06   -1.6e+08      0.000   -6.19e+14   -6.19e+14
x26         5.012e+14   3.25e+06   1.54e+08      0.000    5.01e+14    5.01e+14
x27         -1.48e+14   3.45e+06  -4.28e+07      0.000   -1.48e+14   -1.48e+14
x28         3.664e+13   4.37e+06   8.39e+06      0.000    3.66e+13    3.66e+13
x29         2.953e+13   3.59e+06   8.23e+06      0.000    2.95e+13    2.95e+13
x30        -9.237e+13   3.79e+06  -2.44e+07      0.000   -9.24e+13   -9.24e+13
x31        -8.932e+13   4.93e+06  -1.81e+07      0.000   -8.93e+13   -8.93e+13
x32        -1.501e+14   5.44e+06  -2.76e+07      0.000    -1.5e+14    -1.5e+14
x33         2.757e+14   4.77e+06   5.78e+07      0.000    2.76e+14    2.76e+14
x34         3.375e+14   7.36e+06   4.58e+07      0.000    3.37e+14    3.37e+14
x35         6.274e+14   1.33e+07   4.72e+07      0.000    6.27e+14    6.27e+14
x36         5.792e+14   1.15e+07   5.05e+07      0.000    5.79e+14    5.79e+14
x37         1.808e+14   6.27e+06   2.88e+07      0.000    1.81e+14    1.81e+14
x38         4.712e+13   5.67e+06   8.31e+06      0.000    4.71e+13    4.71e+13
x39          1.13e+14   4.94e+06   2.29e+07      0.000    1.13e+14    1.13e+14
x40         5.636e+14   1.99e+07   2.83e+07      0.000    5.64e+14    5.64e+14
x41         1.108e+15   3.59e+07   3.08e+07      0.000    1.11e+15    1.11e+15
x42         1.019e+15   3.75e+07   2.71e+07      0.000    1.02e+15    1.02e+15
x43         4.549e+12   3.65e+06   1.24e+06      0.000    4.55e+12    4.55e+12
x44        -5.795e+13   3.77e+06  -1.54e+07      0.000   -5.79e+13   -5.79e+13
x45         2.157e+13   3.49e+06   6.18e+06      0.000    2.16e+13    2.16e+13
x46        -1.778e+13   1.91e+06  -9.32e+06      0.000   -1.78e+13   -1.78e+13
x47         1.778e+13   1.91e+06   9.32e+06      0.000    1.78e+13    1.78e+13
x48        -1.015e+14    4.1e+06  -2.48e+07      0.000   -1.01e+14   -1.01e+14
x49         2.814e+14   4.67e+06   6.02e+07      0.000    2.81e+14    2.81e+14
x50         2.669e+14   5.97e+06   4.47e+07      0.000    2.67e+14    2.67e+14
x51         3.428e+14   7.49e+06   4.58e+07      0.000    3.43e+14    3.43e+14
x52         1.509e+14   7.04e+06   2.14e+07      0.000    1.51e+14    1.51e+14
x53         1.752e+14   7.16e+06   2.45e+07      0.000    1.75e+14    1.75e+14
x54         1.222e+13   6.24e+06   1.96e+06      0.000    1.22e+13    1.22e+13
x55         7.956e+13   7.22e+06    1.1e+07      0.000    7.96e+13    7.96e+13
x56        -9.951e+13   5.98e+06  -1.67e+07      0.000   -9.95e+13   -9.95e+13
x57         3.864e+13   5.42e+06   7.13e+06      0.000    3.86e+13    3.86e+13
x58         1.148e+14   5.67e+06   2.02e+07      0.000    1.15e+14    1.15e+14
x59         8.108e+13   3.79e+06   2.14e+07      0.000    8.11e+13    8.11e+13
x60         1.223e+14   1.67e+06   7.32e+07      0.000    1.22e+14    1.22e+14
x61         1.352e+14   3.97e+06    3.4e+07      0.000    1.35e+14    1.35e+14
x62        -9.954e+13   4.04e+06  -2.46e+07      0.000   -9.95e+13   -9.95e+13
x63         4.509e+12   3.48e+06    1.3e+06      0.000    4.51e+12    4.51e+12
x64        -3.693e+13   3.49e+06  -1.06e+07      0.000   -3.69e+13   -3.69e+13
x65         4.311e+13   3.45e+06   1.25e+07      0.000    4.31e+13    4.31e+13
x66        -1.031e+14   3.27e+06  -3.15e+07      0.000   -1.03e+14   -1.03e+14
x67         6.829e+13    3.2e+06   2.13e+07      0.000    6.83e+13    6.83e+13
x68         1.453e+14   3.05e+06   4.77e+07      0.000    1.45e+14    1.45e+14
x69        -1.273e+14   3.32e+06  -3.84e+07      0.000   -1.27e+14   -1.27e+14
x70        -1.747e+14    2.7e+06  -6.46e+07      0.000   -1.75e+14   -1.75e+14
x71        -2.932e+12   1.94e+06  -1.51e+06      0.000   -2.93e+12   -2.93e+12
x72         1.223e+14   1.67e+06   7.32e+07      0.000    1.22e+14    1.22e+14
x73        -1.223e+14   1.67e+06  -7.32e+07      0.000   -1.22e+14   -1.22e+14
x74         2.049e+14   3.53e+06    5.8e+07      0.000    2.05e+14    2.05e+14
x75        -3.165e+14   3.91e+06   -8.1e+07      0.000   -3.16e+14   -3.16e+14
x76         9.888e+13   3.46e+06   2.86e+07      0.000    9.89e+13    9.89e+13
x77         1.528e+14   4.35e+06   3.52e+07      0.000    1.53e+14    1.53e+14
x78        -9.294e+13   4.35e+06  -2.14e+07      0.000   -9.29e+13   -9.29e+13
x79        -3.223e+14   5.21e+06  -6.18e+07      0.000   -3.22e+14   -3.22e+14
x80         2.003e+13   4.77e+06    4.2e+06      0.000       2e+13       2e+13
x81        -3.336e+14   6.74e+06  -4.95e+07      0.000   -3.34e+14   -3.34e+14
x82         -4.51e+13      5e+06  -9.02e+06      0.000   -4.51e+13   -4.51e+13
x83        -8.761e+13   5.08e+06  -1.73e+07      0.000   -8.76e+13   -8.76e+13
x84        -8.771e+12   4.32e+06  -2.03e+06      0.000   -8.77e+12   -8.77e+12
x85         -3.23e+14   4.29e+06  -7.53e+07      0.000   -3.23e+14   -3.23e+14
x86        -1.778e+14   4.57e+06  -3.89e+07      0.000   -1.78e+14   -1.78e+14
x87        -1.301e+14   3.61e+06  -3.61e+07      0.000    -1.3e+14    -1.3e+14
x88        -1.229e+14   3.58e+06  -3.43e+07      0.000   -1.23e+14   -1.23e+14
x89        -3.197e+15   3.39e+06  -9.42e+08      0.000    -3.2e+15    -3.2e+15
x90        -2.865e+14   3.51e+06  -8.16e+07      0.000   -2.86e+14   -2.86e+14
x91         2.445e+13   4.44e+06   5.51e+06      0.000    2.44e+13    2.44e+13
x92        -1.797e+14   3.27e+06   -5.5e+07      0.000    -1.8e+14    -1.8e+14
x93         1.049e+14   3.74e+06   2.81e+07      0.000    1.05e+14    1.05e+14
x94         1.704e+14   4.02e+06   4.24e+07      0.000     1.7e+14     1.7e+14
x95         8.693e+13    4.1e+06   2.12e+07      0.000    8.69e+13    8.69e+13
x96         1.249e+14   4.28e+06   2.92e+07      0.000    1.25e+14    1.25e+14
x97        -1.928e+13   4.13e+06  -4.66e+06      0.000   -1.93e+13   -1.93e+13
x98         9.118e+10   3.99e+06   2.29e+04      0.000    9.12e+10    9.12e+10
x99         4.533e+13   4.64e+06   9.77e+06      0.000    4.53e+13    4.53e+13
x100       -9.457e+12   6.55e+06  -1.44e+06      0.000   -9.46e+12   -9.46e+12
x101       -3.584e+13   6.57e+06  -5.46e+06      0.000   -3.58e+13   -3.58e+13
x102       -4.146e+13   6.39e+06  -6.49e+06      0.000   -4.15e+13   -4.15e+13
x103       -4.576e+14   3.43e+06  -1.34e+08      0.000   -4.58e+14   -4.58e+14
x104        5.643e+13   4.86e+06   1.16e+07      0.000    5.64e+13    5.64e+13
x105       -1.012e+13   4.79e+06  -2.11e+06      0.000   -1.01e+13   -1.01e+13
x106        1.266e+14   4.17e+06   3.03e+07      0.000    1.27e+14    1.27e+14
x107       -2.139e+11   3.68e+06  -5.82e+04      0.000   -2.14e+11   -2.14e+11
x108        1.631e+14   3.72e+06   4.39e+07      0.000    1.63e+14    1.63e+14
x109       -2.594e+14   3.55e+06  -7.32e+07      0.000   -2.59e+14   -2.59e+14
==============================================================================
"""

**3. Obtain the predicted values of the response variable and use them to compute the accuracy rate of your model. Compare it to the accuracy rate you would obtain if you predicted the endline enrollment status by flipping a coin. What is the percentage of improvement in accuracy that you achieve?**

In [37]:
#Compute predicted probabilities
probs_logit = results_logit.predict(X_test_std)

#Transform probabilities into predicted failure/success
Y_pred_logit = np.array([0]*X_test_std.shape[0])
Y_pred_logit[probs_logit>0.5]= 1

#Compute error and accuracy rates
error_rate_logit = np.mean(Y_pred_logit != Y_test)
accuracy_logit = 1 - error_rate_logit
print(accuracy_logit)

#Compute percentage of improvement
imp = (accuracy_logit - 0.5) / 0.5 * 100
print("Percentage of improvement:", imp)

0.5542168674698795
Percentage of improvement: 10.843373493975905

/opt/python/lib/python3.13/site-packages/statsmodels/genmod/families/links.py:198: RuntimeWarning: overflow encountered in exp
  t = np.exp(-z)

**4. Fit a LASSO model to the same data, using the same predictors. Use 5-fold cross-validation to select the optimal lambda and a validation set to obtain a test MSE. Always use a seed of 3.**

In [38]:
# Create Y and X
Y = df['m_gq_dropout']
X = df[features]

# Create search grid for tuning parameter (lambda)
lambdas = 10**np.linspace(8, -2, 100) / Y.std()

# Choose splitting rule for outer split (train set vs. test set)
outer_valid = skm.ShuffleSplit(n_splits=1, 
                               test_size=0.25,
                               random_state=3)

# Choose splitting rule for cross-validation step (used to select optimal lambda)
inner_cv = skm.KFold(n_splits=5,
                     shuffle=True,
                     random_state=3)

# Program lasso regression with lambda selected based on inner_CV
lassoCV = skl.ElasticNetCV(alphas=lambdas,
                           l1_ratio=1,
                           cv=inner_cv)

# Standardize predictors: 
scaler = StandardScaler(with_mean=True,  with_std=True)
pipeCV = Pipeline(steps=[('scaler', scaler),
                         ('lasso', lassoCV)])

# Obtain fitted model from validation set using outer split
results_lasso = skm.cross_validate(pipeCV, 
                             X,
                             Y,
                             cv=outer_valid,
                             scoring='neg_mean_squared_error',
                             return_estimator=True) #Add this line to store estimator results

est = results_lasso['estimator'][0]

**5. Obtain the predicted values of the response variable and use them to compute the accuracy rate of your LASSO model. Compare it to the accuracy rate of your logit model. What is the percentage of improvement in accuracy that you achieve?**

In [42]:
#Obtain matrix of predictor values for the test sample in the outer split
for train_idx, test_idx in outer_valid.split(X):

    X_train_lasso, X_test_lasso = X.iloc[train_idx], X.iloc[test_idx]
    Y_train_lasso, Y_test_lasso = Y.iloc[train_idx], Y.iloc[test_idx]

#Compute success probabilities and convert them to dummy
prob_lasso = est.predict(X_test_lasso)
Y_pred_lasso = np.array([0]*X_test_lasso.shape[0])
Y_pred_lasso[prob_lasso>0.5]= 1

#Compute accuracy rate of LASSO
error_rate_lasso = np.mean(Y_pred_lasso != Y_test_lasso)
accuracy_lasso = 1 - error_rate_lasso
print(accuracy_lasso)
np.mean(Y_test)

#Compute percentage of improvement over coin
imp_coin = (accuracy_lasso - 0.5) / 0.5 * 100
print("Percentage of improvement over coin:", imp_coin)

#Compute percentage of improvement over logit
imp_logit = (accuracy_lasso - accuracy_logit) / accuracy_logit * 100
print("Percentage of improvement over logit:", imp_logit)

0.608433734939759
Percentage of improvement over coin: 21.68674698795181
Percentage of improvement over logit: 9.782608695652176

**6. Create a dataframe containing one column for the labels of predictor variables and another one with the coefficients on each predictor variable in the trained LASSO model. What is the predictor for which the coefficient has the largest absolute value? Hint : you can use DataFrame.sort_values(by = '', ascending=False) to sort your dataframe (replace DataFrame by the name of your dataframe and pass the name of the column on which you want to sort to the by argument)**

In [43]:
#Print selected coefs
selected_coefs = est.named_steps['lasso'].coef_
coefs = pd.DataFrame({'coefs': selected_coefs, 'labels': features})
coefs = coefs.sort_values(by='coefs', ascending=False)
coefs

       coefs                  labels
40  0.009134  b_gq_g_Index_auto_cat3
76  0.002621        b_gq_c_40_all_16
25  0.000568            b_gq_c1_ever
17  0.000095              b_gq_age17
2  -0.000000           b_hq_a2_brick
..       ...                     ...
84 -0.010893        b_gq_c_40_all_24
1  -0.013641           b_hq_a2_stone
55 -0.015289        b_hq_hh_b9_60_65
61 -0.021764        b_hq_hh_b10_wido
74 -0.067766            b_hq_a6g_dum

[109 rows x 2 columns]

The coefficient with the largest absolute magnitude is the coefficient on b_hq_a6g_dum (TV ownership dummy).